/**
 * 30 Ganesh Chaturthi bangers, dhol-tasha cuts, and aarti staples.
 * Playback is always via YouTube (video IDs only — no audio files hosted here).
 * The order is intentional: Ya Re Ya opens the mandap, then the queue moves
 * through procession energy, Marathi classics, aartis, and mantras.
 */
window.GANESH_SONGS = [
  {
    id: "HzGE_WaSqE4",
    youtubeId: "HzGE_WaSqE4",
    title: "Ya Re Ya",
    artist: "Rohan-Rohan",
    album: "Ventilator",
  },
  {
    id: "YiiV0XWCtFw",
    youtubeId: "YiiV0XWCtFw",
    title: "Aarambh",
    artist: "Pritam S K Patil · Ashish Kulkarni",
    album: "Ganpati Song",
  },
  {
    id: "HV5KrQNak-w",
    youtubeId: "HV5KrQNak-w",
    title: "Ganraj Rangi Nachato",
    artist: "Lata Mangeshkar",
    album: "Ganapati Aarti",
  },
  {
    id: "CqEoGLs6JfU",
    youtubeId: "CqEoGLs6JfU",
    title: "Gajananaa Gajananaa",
    artist: "Shankar Mahadevan",
    album: "Lokmanya · Ek Yugpurush",
  },
  {
    id: "ziN-lFAuaLs",
    youtubeId: "ziN-lFAuaLs",
    title: "Aala Aala Bappa Aala",
    artist: "Mangesh Desai",
    album: "Ekk Albela",
  },
  {
    id: "dCjlQ-cOs-M",
    youtubeId: "dCjlQ-cOs-M",
    title: "Aale Aale Ho Ganpati",
    artist: "Suresh Wadkar",
    album: "Ganesh Chaturthi Song 2025",
  },
  {
    id: "IUzRhOJScuc",
    youtubeId: "IUzRhOJScuc",
    title: "Sur Niragas Ho",
    artist: "Shankar Mahadevan · Anandi Joshi",
    album: "Katyar Kaljat Ghusali",
  },
  {
    id: "Yjd9KmmWQ8k",
    youtubeId: "Yjd9KmmWQ8k",
    title: "Bappa Morya Re",
    artist: "Prahlad Shinde · DJ NeSH",
    album: "Bappa Morya Re",
  },
  {
    id: "SU8bzZad1Ec",
    youtubeId: "SU8bzZad1Ec",
    title: "Devaraya",
    artist: "Shankar Mahadevan",
    album: "Dhol Taashe",
  },
  {
    id: "NVhuAgGIeRI",
    youtubeId: "NVhuAgGIeRI",
    title: "Naad Ninaadala Re Morya",
    artist: "Anand Shinde · DJ Kamlesh Solapur",
    album: "Dhol Tasha Mix",
  },
  {
    id: "8hyHYNyhahQ",
    youtubeId: "8hyHYNyhahQ",
    title: "Ganpati Bappa Morya",
    artist: "Tejas Padave · Sneha Mahadik",
    album: "Ganpati Bappa Morya · 2025",
  },
  {
    id: "mFbI4kRQ1nU",
    youtubeId: "mFbI4kRQ1nU",
    title: "Om Ganapataye Namaha Deva",
    artist: "Vishal Dadlani · Nakash Aziz",
    album: "Banjo",
  },
  {
    id: "r7SGSHzakBE",
    youtubeId: "r7SGSHzakBE",
    title: "Gaurinandan Lambodara Re",
    artist: "Rohit Raut",
    album: "Ganpati Song",
  },
  {
    id: "6v3nrmvAoYQ",
    youtubeId: "6v3nrmvAoYQ",
    title: "Gajanana Tu Moraya",
    artist: "P Shankaram",
    album: "Ganpati Song",
  },
  {
    id: "6HdTWW3p1eA",
    youtubeId: "6HdTWW3p1eA",
    title: "Atharvashirsha",
    artist: "Shankar Mahadevan",
    album: "Lokmat Ti Cha Ganpati",
  },
  {
    id: "ZlzfmptxQ4w",
    youtubeId: "ZlzfmptxQ4w",
    title: "Gan Gan Ganat Bote",
    artist: "Traditional · Gajanan Maharaj",
    album: "Marathi Devotional",
  },
  {
    id: "CUHjVe7HN0Q",
    youtubeId: "CUHjVe7HN0Q",
    title: "Tuch Gajavadana",
    artist: "Mangesh Borgaonkar",
    album: "Ganpati Song",
  },
  {
    id: "esBHy_ky-PQ",
    youtubeId: "esBHy_ky-PQ",
    title: "Dhol Dhol (Morya Morya)",
    artist: "Adarsh Shinde",
    album: "Me Yetoy… Chhota Pudhari",
  },
  {
    id: "fMHIN0KIoCs",
    youtubeId: "fMHIN0KIoCs",
    title: "Pratham Tula Vandito",
    artist: "Suresh Bapat · Madhuri Mahajan",
    album: "Bappa Morya Re",
  },
  {
    id: "IqhepuMHxRA",
    youtubeId: "IqhepuMHxRA",
    title: "Deva Ho Deva",
    artist: "Sukhwinder Singh · Divya Kumar",
    album: "Bhikari",
  },
  {
    id: "lae0Lue9exk",
    youtubeId: "lae0Lue9exk",
    title: "Shree Ganpatichi Aarti",
    artist: "Lata Mangeshkar",
    album: "Essential Ganesha",
  },
  {
    id: "kmmmZn4cQmU",
    youtubeId: "kmmmZn4cQmU",
    title: "Ghalin Lotangan",
    artist: "Ajay-Atul",
    album: "Ganesh Aarti",
  },
  {
    id: "m-XMZF01ugs",
    youtubeId: "m-XMZF01ugs",
    title: "Bappa Bol Re",
    artist: "Avadhoot Gupte · Saurabh Daftardar",
    album: "Appa Ani Bappa",
  },
  {
    id: "HQZAWsA-Y5E",
    youtubeId: "HQZAWsA-Y5E",
    title: "Aala Vajat Gajat Bappa Ganpati",
    artist: "Vikas Mahajan · Raju Yashwant",
    album: "Ganpati Song",
  },
  {
    id: "2rA2YMX-4L0",
    youtubeId: "2rA2YMX-4L0",
    title: "Sri Ganesh Stotram",
    artist: "The Art of Living",
    album: "Ganpati Stotram",
  },
  {
    id: "HE5SE4farrQ",
    youtubeId: "HE5SE4farrQ",
    title: "Maza Bappa Aala",
    artist: "Zee Music Marathi",
    album: "Ganpati Aagman",
  },
  {
    id: "cGcw33hVrS4",
    youtubeId: "cGcw33hVrS4",
    title: "Bappa",
    artist: "Vishal & Shekhar · Vishal Dadlani",
    album: "Banjo",
  },
  {
    id: "KJF8t-BWVRM",
    youtubeId: "KJF8t-BWVRM",
    title: "Gajanana",
    artist: "Sukhwinder Singh",
    album: "Bajirao Mastani",
  },
  {
    id: "VJPLXBvV4qQ",
    youtubeId: "VJPLXBvV4qQ",
    title: "Ganapati Tu Sarvashreshth",
    artist: "Adesh Karwarkar",
    album: "Marathi Ganpati Song",
  },
  {
    id: "zL0UOX5vGYI",
    youtubeId: "zL0UOX5vGYI",
    title: "Ganpati Tu Gunapati Tu",
    artist: "Vasantrao Deshpande",
    album: "Marathi Devotional Song",
  },
];
