/**
 * 30 Ganesh Chaturthi bangers, dhol-tasha cuts, and aarti staples.
 * Playback is always via YouTube (video IDs only — no audio files hosted here).
 * The order is intentional: Ya Re Ya opens the mandap, then the queue moves
 * through procession energy, Marathi classics, aartis, and mantras.
 */
window.GANESH_SONGS = [
  {
    id: "HzGE_WaSqE4",
    youtubeId: "HzGE_WaSqE4",
    title: "Ya Re Ya",
    artist: "Rohan-Rohan",
    album: "Ventilator",
  },
  {
    id: "XgcMujMnoQU",
    youtubeId: "XgcMujMnoQU",
    title: "Ganpati Majha Nachat Aala",
    artist: "Anand Shinde",
    album: "Ganpati Majha Nachat Aala",
  },
  {
    id: "HV5KrQNak-w",
    youtubeId: "HV5KrQNak-w",
    title: "Ganraj Rangi Nachato",
    artist: "Lata Mangeshkar",
    album: "Ganapati Aarti",
  },
  {
    id: "CqEoGLs6JfU",
    youtubeId: "CqEoGLs6JfU",
    title: "Gajananaa Gajananaa",
    artist: "Shankar Mahadevan",
    album: "Lokmanya · Ek Yugpurush",
  },
  {
    id: "XmS9GTQuAhs",
    youtubeId: "XmS9GTQuAhs",
    title: "Deva Shree Ganesha",
    artist: "Ajay-Atul · Ajay Gogavale",
    album: "Agneepath",
  },
  {
    id: "GrVOG4POsko",
    youtubeId: "GrVOG4POsko",
    title: "Mourya Re",
    artist: "Shankar Mahadevan",
    album: "Don",
  },
  {
    id: "DPH4r-nRNE0",
    youtubeId: "DPH4r-nRNE0",
    title: "Morya Morya",
    artist: "Ajay-Atul",
    album: "Uladhaal",
  },
  {
    id: "Yjd9KmmWQ8k",
    youtubeId: "Yjd9KmmWQ8k",
    title: "Bappa Morya Re",
    artist: "Prahlad Shinde · DJ NeSH",
    album: "Bappa Morya Re",
  },
  {
    id: "SU8bzZad1Ec",
    youtubeId: "SU8bzZad1Ec",
    title: "Devaraya",
    artist: "Shankar Mahadevan",
    album: "Dhol Taashe",
  },
  {
    id: "NVhuAgGIeRI",
    youtubeId: "NVhuAgGIeRI",
    title: "Naad Ninaadala Re Morya",
    artist: "Anand Shinde · DJ Kamlesh Solapur",
    album: "Dhol Tasha Mix",
  },
  {
    id: "8hyHYNyhahQ",
    youtubeId: "8hyHYNyhahQ",
    title: "Ganpati Bappa Morya",
    artist: "Tejas Padave · Sneha Mahadik",
    album: "Ganpati Bappa Morya · 2025",
  },
  {
    id: "DYG0AbBOYLI",
    youtubeId: "DYG0AbBOYLI",
    title: "Maza Bappa Shree",
    artist: "Shaan",
    album: "Ganpati Song",
  },
  {
    id: "q72FRIUFcvM",
    youtubeId: "q72FRIUFcvM",
    title: "Sukhkarta Dukhharta",
    artist: "Anuradha Paudwal",
    album: "Aarti & Bhajan",
  },
  {
    id: "vVgz3Pg-EMs",
    youtubeId: "vVgz3Pg-EMs",
    title: "Shendur Laal Chadhayo",
    artist: "Ravindra Sathe",
    album: "Vaastav · Ganesh Aarti",
  },
  {
    id: "re88S-5fpmA",
    youtubeId: "re88S-5fpmA",
    title: "Ekadantaya Vakratundaya",
    artist: "Shankar Mahadevan",
    album: "Ganeshotsav Special",
  },
  {
    id: "ZlzfmptxQ4w",
    youtubeId: "ZlzfmptxQ4w",
    title: "Gan Gan Ganat Bote",
    artist: "Traditional · Gajanan Maharaj",
    album: "Marathi Devotional",
  },
  {
    id: "J0uvj4Y_emA",
    youtubeId: "J0uvj4Y_emA",
    title: "Aala Re Aala Ganpati",
    artist: "Sachin · Suresh Wadkar",
    album: "Amachya Sarkhe Aamicha",
  },
  {
    id: "esBHy_ky-PQ",
    youtubeId: "esBHy_ky-PQ",
    title: "Dhol Dhol (Morya Morya)",
    artist: "Adarsh Shinde",
    album: "Me Yetoy… Chhota Pudhari",
  },
  {
    id: "fMHIN0KIoCs",
    youtubeId: "fMHIN0KIoCs",
    title: "Pratham Tula Vandito",
    artist: "Suresh Bapat · Madhuri Mahajan",
    album: "Bappa Morya Re",
  },
  {
    id: "N4Ilw97aKn0",
    youtubeId: "N4Ilw97aKn0",
    title: "Tuz Magato Mee Aata",
    artist: "Lata Mangeshkar",
    album: "Ganesh Bhajan",
  },
  {
    id: "lae0Lue9exk",
    youtubeId: "lae0Lue9exk",
    title: "Shree Ganpatichi Aarti",
    artist: "Lata Mangeshkar",
    album: "Essential Ganesha",
  },
  {
    id: "kmmmZn4cQmU",
    youtubeId: "kmmmZn4cQmU",
    title: "Ghalin Lotangan",
    artist: "Ajay-Atul",
    album: "Ganesh Aarti",
  },
  {
    id: "2ZkOuT26buk",
    youtubeId: "2ZkOuT26buk",
    title: "Om Gan Ganpatye Namo Namah",
    artist: "Suresh Wadkar",
    album: "Ganesh Mantra",
  },
  {
    id: "OOWveA63cjI",
    youtubeId: "OOWveA63cjI",
    title: "Ganesh Tandav Stotram",
    artist: "Shankar Mahadevan · Shailesh Dani",
    album: "Ganesh Utsav 2025",
  },
  {
    id: "wCgrmd9mDxE",
    youtubeId: "wCgrmd9mDxE",
    title: "Shree Ganeshay Dheemahi",
    artist: "Ajay-Atul · Shankar Mahadevan",
    album: "Vishwa Vinayak",
  },
  {
    id: "HE5SE4farrQ",
    youtubeId: "HE5SE4farrQ",
    title: "Maza Bappa Aala",
    artist: "Zee Music Marathi",
    album: "Ganpati Aagman",
  },
  {
    id: "cGcw33hVrS4",
    youtubeId: "cGcw33hVrS4",
    title: "Bappa",
    artist: "Vishal & Shekhar · Vishal Dadlani",
    album: "Banjo",
  },
  {
    id: "KJF8t-BWVRM",
    youtubeId: "KJF8t-BWVRM",
    title: "Gajanana",
    artist: "Sukhwinder Singh",
    album: "Bajirao Mastani",
  },
  {
    id: "VJPLXBvV4qQ",
    youtubeId: "VJPLXBvV4qQ",
    title: "Ganapati Tu Sarvashreshth",
    artist: "Adesh Karwarkar",
    album: "Marathi Ganpati Song",
  },
  {
    id: "_jiTr71_X8c",
    youtubeId: "_jiTr71_X8c",
    title: "Ganpati Mantra",
    artist: "Shankar Mahadevan",
    album: "Ganesh Pancharatna Stotra",
  },
];
